Make install workflow is failing (vibe-kanban 10b63591)
\`\`\`

```javascript
Run make install
```

```javascript
Installing client dependencies...
```

```javascript
yarn install v1.22.22
```

```javascript
info No lockfile found.
```

```javascript
[1/4] Resolving packages...
```

```javascript
warning svelte-carousel > easy-reactive > lodash.isequal@4.5.0: This package is deprecated. Use require('node:util').isDeepStrictEqual instead.
```

```javascript
warning svelte-carousel > easy-reactive > lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
```

```javascript
warning eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
```

```javascript
warning eslint > @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
```

```javascript
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
```

```javascript
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
```

```javascript
warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
```

```javascript
warning eslint > file-entry-cache > flat-cache > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
```

```javascript
warning eslint-config-standard-with-typescript@43.0.1: Please use eslint-config-love, instead.
```

```javascript
warning svelte-check > svelte-preprocess > sorcery > sander > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
```

```javascript
warning svelte-check > svelte-preprocess > sorcery > sander > rimraf > glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
```

```javascript
[2/4] Fetching packages...
```

```javascript
[3/4] Linking dependencies...
```

```javascript
warning "@playwright/experimental-ct-svelte > @sveltejs/vite-plugin-svelte@5.1.1" has incorrect peer dependency "svelte@^5.0.0".
```

```javascript
warning "@playwright/experimental-ct-svelte > @sveltejs/vite-plugin-svelte@5.1.1" has incorrect peer dependency "vite@^6.0.0".
```

```javascript
warning "@playwright/experimental-ct-svelte > @sveltejs/vite-plugin-svelte > @sveltejs/vite-plugin-svelte-inspector@4.0.1" has incorrect peer dependency "svelte@^5.0.0".
```

```javascript
warning "@playwright/experimental-ct-svelte > @sveltejs/vite-plugin-svelte > @sveltejs/vite-plugin-svelte-inspector@4.0.1" has incorrect peer dependency "vite@^6.0.0".
```

```javascript
warning Workspaces can only be enabled in private projects.
```

```javascript
[4/4] Building fresh packages...
```

```javascript
success Saved lockfile.
```

```javascript
Done in 29.75s.
```

```javascript
Client dependencies installed successfully!
```

```javascript
Installing server dependencies...
```

```javascript
/bin/sh: 1: bun: not found
```

```javascript
make: *** [Makefile:9: install-server] Error 1
```

```javascript
Error: Process completed with exit code 2.
```

this is my github workflow result, i suppose set up bun should be added in workflow file to fix this
\`\`\`