Fix db migration seed (vibe-kanban e9e120da)
```javascript
$ nest build && typeorm-ts-node-commonjs migration:run -d typeorm.config.ts

src/database/seeder/defaultSeedValues.ts:129:3 - error TS2739: Type '{ id: string; exchange_id: string; symbol: string; base_symbol: string; quote_symbol: string; base_asset_id: string; base_icon_url: string; quote_asset_id: string; quote_icon_url: string; base_price: string; target_price: string; custom_fee_rate: string; enable: true; }' is missing the following properties from type 'GrowdataMarketMakingPair': base_chain_id, base_chain_icon_url, quote_chain_id, quote_chain_icon_url

129   {

      ~

130     id: '7fef38d5-5644-42e9-9abb-9f8e1a51ff36',

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

144     enable: true,

    ~~~~~~~~~~~~~~~~~

145   },

    ~~~

src/database/seeder/defaultSeedValues.ts:146:3 - error TS2739: Type '{ id: string; exchange_id: string; symbol: string; base_symbol: string; quote_symbol: string; base_asset_id: string; base_icon_url: string; quote_asset_id: string; quote_icon_url: string; base_price: string; target_price: string; custom_fee_rate: string; enable: true; }' is missing the following properties from type 'GrowdataMarketMakingPair': base_chain_id, base_chain_icon_url, quote_chain_id, quote_chain_icon_url

146   {

      ~

147     id: 'ce5d8591-4ed0-4286-a390-c4ba254e442a',

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

161     enable: true,

    ~~~~~~~~~~~~~~~~~

162   },

    ~~~

src/database/seeder/defaultSeedValues.ts:163:3 - error TS2739: Type '{ id: string; exchange_id: string; symbol: string; base_symbol: string; quote_symbol: string; base_asset_id: string; base_icon_url: string; quote_asset_id: string; quote_icon_url: string; base_price: string; target_price: string; custom_fee_rate: string; enable: true; }' is missing the following properties from type 'GrowdataMarketMakingPair': base_chain_id, base_chain_icon_url, quote_chain_id, quote_chain_icon_url

163   {

      ~

164     id: '8c60b47e-e77c-4068-962f-e542c9919af4',

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

178     enable: true,

    ~~~~~~~~~~~~~~~~~

179   },

    ~~~

src/database/seeder/defaultSeedValues.ts:180:3 - error TS2739: Type '{ id: string; exchange_id: string; symbol: string; base_symbol: string; quote_symbol: string; base_asset_id: string; base_icon_url: string; quote_asset_id: string; quote_icon_url: string; base_price: string; target_price: string; custom_fee_rate: string; enable: true; }' is missing the following properties from type 'GrowdataMarketMakingPair': base_chain_id, base_chain_icon_url, quote_chain_id, quote_chain_icon_url

180   {

      ~

181     id: '460dc888-ed7e-451c-acf2-44099065faf4',

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```javascript
...

195     enable: true,

    ~~~~~~~~~~~~~~~~~

196   },

    ~~~

Found 4 error(s).

error: script "migration:run" exited with code 1

Error: Process completed with exit code 1.
```